services:
  - type: web
    name: refgd
    rootDir: refgd
    buildCommand: npm install && npm run build
    startCommand: npm start
    env: node
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
